### PR TITLE
update logo picture assets

### PR DESCRIPTION
**Pull request by taiwoobe**

### CODE REVIEW

**Review by crmne — CHANGES_REQUESTED** [review]
Can we make `img`s automatically use the retina version if available?

The image names should be {1xname}@2x.{format}

**Comment by taiwoobe** [comment]
> 

But the srcset would determine the screen resolution and automatically render the 2x retina when available. If we set the default to use the retina, then we might as well just remove the 1x and only use the 2x.

**Comment by crmne** [comment]
Oh, let me clarify:

Instead of adding the srcset to each specific image, can we use a class to do this automatically for each image?

**Comment by taiwoobe** [comment]
> Oh, let me clarify:
> 
> Instead of adding the srcset to each specific image, can we use a class to do this automatically for each image?

I dont think this would be a viable solution. Using classes to load an image would kill the responsive property that picture element provides with srcset. Check here - https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

We can have a short call if this doesnt clarify things.

**Pull request merged**
