### PR TITLE
fix blog logo

### PR DESCRIPTION
**Pull request by taiwoobe**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1201889865668445

### CODE REVIEW

**Comment by crmne** [comment]
Hi @taiwoobe, it looks like the logo issue is solved, but the banner of the blog is repeated twice

**Comment by crmne** [comment]
Screenshot 2022-03-13 at 14 30 01

**Comment by taiwoobe** [comment]
Fixed now. Some js error

**Comment by crmne** [comment]
great, tested and it works

**Pull request merged**
